#!/usr/bin/env python3
"""Send success / failure email via Gmail SMTP using app password.

Usage:
  python3 send_email.py success
  python3 send_email.py failure

Required env vars:
  GMAIL_USERNAME, GMAIL_APP_PASSWORD, MAIL_TO

Success-only env vars (passed by workflow):
  RUN_NUMBER, REPORT_WEEK, PAYMENTS, NET_SALES, TRANSACTIONS,
  LABOR_PCT, OP_MARGIN, DQ_STATUS

Failure-only env vars:
  RUN_NUMBER, GH_RUN_URL
"""
import os, sys, smtplib
from email.message import EmailMessage

REPORT_URL = 'https://pour-decisions-report.vercel.app'

def fmt_money(s):
    try:
        return f"${float(s):,.2f}"
    except Exception:
        return s or '?'

def fmt_int(s):
    try:
        return f"{int(float(s)):,}"
    except Exception:
        return s or '?'

def fmt_pct(s):
    try:
        return f"{float(s):.1f}%"
    except Exception:
        return s or '?'

def build_success():
    week = os.environ.get('REPORT_WEEK', '?')
    run_n = os.environ.get('RUN_NUMBER', '?')
    payments = fmt_money(os.environ.get('PAYMENTS'))
    net = fmt_money(os.environ.get('NET_SALES'))
    txns = fmt_int(os.environ.get('TRANSACTIONS'))
    labor = fmt_pct(os.environ.get('LABOR_PCT'))
    margin = fmt_pct(os.environ.get('OP_MARGIN'))
    dq = os.environ.get('DQ_STATUS', 'UNKNOWN')

    subject = f"Pour Decisions Weekly Report — Run #{run_n} — {week}"
    text = f"""Pour Decisions Weekly Report — Run #{run_n}

Week: {week}

Total Payments:   {payments}
Net Sales:        {net}
Transactions:     {txns}
Labor % of Net:   {labor}
Op Margin:        {margin}
Data Quality:     {dq}

View report: {REPORT_URL}
"""
    html = f"""<!doctype html>
<html><body style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;background:#f5f6fa;padding:24px;color:#1B2A4A;">
  <div style="max-width:560px;margin:0 auto;background:#fff;border-radius:12px;padding:28px;box-shadow:0 2px 8px rgba(0,0,0,.06);">
    <h1 style="margin:0 0 4px 0;font-size:20px;color:#1B2A4A;">Pour Decisions Weekly Report</h1>
    <div style="color:#6b7280;font-size:13px;margin-bottom:18px;">Run #{run_n} — {week}</div>

    <table style="width:100%;border-collapse:collapse;font-size:14px;">
      <tr><td style="padding:8px 0;color:#6b7280;">Total Payments</td><td style="padding:8px 0;text-align:right;font-weight:600;">{payments}</td></tr>
      <tr><td style="padding:8px 0;color:#6b7280;">Net Sales</td><td style="padding:8px 0;text-align:right;font-weight:600;">{net}</td></tr>
      <tr><td style="padding:8px 0;color:#6b7280;">Transactions</td><td style="padding:8px 0;text-align:right;font-weight:600;">{txns}</td></tr>
      <tr><td style="padding:8px 0;color:#6b7280;">Labor % of Net</td><td style="padding:8px 0;text-align:right;font-weight:600;">{labor}</td></tr>
      <tr><td style="padding:8px 0;color:#6b7280;">Op Margin</td><td style="padding:8px 0;text-align:right;font-weight:600;">{margin}</td></tr>
      <tr><td style="padding:8px 0;color:#6b7280;">Data Quality</td><td style="padding:8px 0;text-align:right;font-weight:600;color:{'#2ECC71' if dq=='PASS' else '#D4A853' if dq=='WARN' else '#E74C3C'};">{dq}</td></tr>
    </table>

    <div style="margin-top:24px;text-align:center;">
      <a href="{REPORT_URL}" style="display:inline-block;background:#1B2A4A;color:#fff;text-decoration:none;padding:12px 24px;border-radius:8px;font-weight:600;">View Full Report</a>
    </div>

    <div style="margin-top:24px;color:#9ca3af;font-size:12px;text-align:center;">
      Generated by GitHub Actions · pour-decisions-report
    </div>
  </div>
</body></html>"""
    return subject, text, html


def build_failure():
    run_n = os.environ.get('RUN_NUMBER', '?')
    url = os.environ.get('GH_RUN_URL', '')
    subject = f"[FAILED] Pour Decisions Weekly Report — Run #{run_n}"
    text = f"""The weekly Pour Decisions report failed.

Run number: {run_n}
Workflow logs: {url}
"""
    html = f"""<!doctype html>
<html><body style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;background:#f5f6fa;padding:24px;color:#1B2A4A;">
  <div style="max-width:560px;margin:0 auto;background:#fff;border-radius:12px;padding:28px;box-shadow:0 2px 8px rgba(0,0,0,.06);border-top:4px solid #E74C3C;">
    <h1 style="margin:0 0 4px 0;font-size:20px;color:#E74C3C;">Weekly Report Failed</h1>
    <div style="color:#6b7280;font-size:13px;margin-bottom:18px;">Run #{run_n}</div>
    <p style="font-size:14px;line-height:1.6;">The Pour Decisions weekly report workflow failed. Open the GitHub Actions run for full logs.</p>
    <div style="margin-top:20px;text-align:center;">
      <a href="{url}" style="display:inline-block;background:#E74C3C;color:#fff;text-decoration:none;padding:12px 24px;border-radius:8px;font-weight:600;">View Failed Run</a>
    </div>
  </div>
</body></html>"""
    return subject, text, html


def main():
    mode = sys.argv[1] if len(sys.argv) > 1 else 'success'
    user = os.environ.get('GMAIL_USERNAME')
    pw = os.environ.get('GMAIL_APP_PASSWORD')
    to = os.environ.get('MAIL_TO', user)
    if not user or not pw:
        print('GMAIL_USERNAME / GMAIL_APP_PASSWORD missing — skipping email')
        return
    if mode == 'failure':
        subject, text, html = build_failure()
    else:
        subject, text, html = build_success()

    msg = EmailMessage()
    msg['Subject'] = subject
    msg['From'] = user
    msg['To'] = to
    msg.set_content(text)
    msg.add_alternative(html, subtype='html')

    with smtplib.SMTP_SSL('smtp.gmail.com', 465) as s:
        s.login(user, pw)
        s.send_message(msg)
    print(f'Sent {mode} email to {to}')


if __name__ == '__main__':
    main()
